[package]
name = "scpi-server"
version = "1.0.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]

[dependencies]
env_logger = "0.5"
log = "0.4"
redpitaya = "0.24"

[dependencies.clippy]
version = "*"
optional = true
