[package]
name = "scpi-server"
version = "1.0.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]

[dependencies]
env_logger = "0.7"
log = "0.4"
redpitaya = "0.26"

[badges]
travis-ci = { repository = "yellow-pitaya/scpi-servere" }
